### ISSUE TITLE
 raise pickle.UnpicklingError( _pickle.UnpicklingError: Failed to interpret file '../data\\fingerprints.npy' as a pickle

### ISSUE THREAD

**Issue by Lancelot-Yao-0728** [fabianbalsiger/mrf-reconstruction-media2020#19]
I ran into this problem when running create_dataset.py

**Comment by fabianbalsiger** [comment]
Hi,

it looks like it is some path problem: `'../data\\fingerprints.npy'`. Note the `/` and  `\\` Are you working on Windows?

Best,
Fabian

**Comment by Lancelot-Yao-0728** [comment]
> 你好，
> 
> 看起来这是一些路径问题：`'../data\\fingerprints.npy'`。请注意`/`和 `\\`您在 Windows 上工作吗？
> 
> 最好的， 法比安

Thanks for the reply, my problem has been solved due to the corruption of fingerprints.npy in the master file downloaded from GitHub!
